import type { MapSector } from './types';
import { ResourceType } from './types';

export const MAP_DATA: MapSector[] = [
    {
        id: 'sector-0',
        name: 'Home Roost',
        art: '🏠',
        description: 'Your starting perch. Humble, but full of potential.',
        isUnlocked: true,
        resources: { [ResourceType.Crumbs]: 5 },
        rivalPresence: 0,
        noise: 10,
        maxInfrastructureSlots: 2,
        buildings: [],
        position: { x: 50, y: 50 },
    },
    {
        id: 'sector-1',
        name: 'Town Square Fountain',
        art: '⛲',
        description: 'A place of public gathering and discarded snacks.',
        isUnlocked: false,
        resources: { [ResourceType.Crumbs]: 10, [ResourceType.Faith]: 2 },
        rivalPresence: 20,
        noise: 60,
        maxInfrastructureSlots: 3,
        buildings: [],
        position: { x: 55, y: 40 },
    },
    {
        id: 'sector-2',
        name: 'Bakery Rooftop',
        art: '🥐',
        description: 'The intoxicating aroma of baking bread strengthens belief.',
        isUnlocked: false,
        resources: { [ResourceType.Crumbs]: 15 },
        rivalPresence: 10,
        noise: 30,
        maxInfrastructureSlots: 1,
        buildings: [],
        position: { x: 40, y: 45 },
    },
    {
        id: 'sector-3',
        name: 'Gloomy Alleyway',
        art: '🧱',
        description: 'A dark and dangerous place, rumored to be a den of heresy.',
        isUnlocked: false,
        resources: {},
        rivalPresence: 50,
        noise: 70,
        maxInfrastructureSlots: 1,
        buildings: [],
        position: { x: 35, y: 60 },
    },
    {
        id: 'sector-4',
        name: 'Radio Tower',
        art: '📡',
        description: 'A perfect spot to broadcast the holy coo and expand the Antenna Network.',
        isUnlocked: false,
        resources: { [ResourceType.Faith]: 10 },
        rivalPresence: 15,
        noise: 80,
        maxInfrastructureSlots: 4,
        buildings: [],
        position: { x: 70, y: 30 },
    },
    {
        id: 'sector-5',
        name: 'Grand Library Eaves',
        art: '🏛️',
        description: 'A quiet place for contemplation. Ideal for establishing Pilgrim Routes.',
        isUnlocked: false,
        resources: { [ResourceType.Faith]: 5 },
        rivalPresence: 5,
        noise: 5,
        maxInfrastructureSlots: 2,
        buildings: [],
        position: { x: 65, y: 65 },
    },
    {
        id: 'sector-6',
        name: 'Industrial Scrapyard',
        art: '⚙️',
        description: 'Loud and chaotic, but full of useful junk for Crumb Transport Systems.',
        isUnlocked: false,
        resources: { [ResourceType.Crumbs]: 20 },
        rivalPresence: 40,
        noise: 95,
        maxInfrastructureSlots: 3,
        buildings: [],
        position: { x: 20, y: 35 },
    }
];
