import type { Skill } from './types';

export const SKILLS_DATA: Record<string, Skill> = {
    // --- AUTOMATION TREE ---
    'auto-1': {
        id: 'auto-1',
        name: 'Crumb Efficiency',
        description: 'Followers produce 10% more crumbs.',
        art: '🍞+',
        tree: 'Automation',
        cost: 1,
        unlocked: false,
        dependencies: [],
        position: { row: 1, col: 1 },
    },
    'auto-2': {
        id: 'auto-2',
        name: 'Faithful Automation',
        description: 'Buildings produce 10% more faith.',
        art: '🙏+',
        tree: 'Automation',
        cost: 2,
        unlocked: false,
        dependencies: ['auto-1'],
        position: { row: 2, col: 1 },
    },

    // --- PROPAGANDA TREE ---
    'prop-1': {
        id: 'prop-1',
        name: 'Inspiring Coo',
        description: 'Sermon cards have a 10% chance to attract an extra follower.',
        art: '🗣️+',
        tree: 'Propaganda',
        cost: 1,
        unlocked: false,
        dependencies: [],
        position: { row: 1, col: 1 },
    },
    'prop-2': {
        id: 'prop-2',
        name: 'Morale Boost',
        description: 'Blessing cards are 20% more effective.',
        art: '✨+',
        tree: 'Propaganda',
        cost: 2,
        unlocked: false,
        dependencies: ['prop-1'],
        position: { row: 2, col: 1 },
    },

    // --- COMBAT TREE ---
    'combat-1': {
        id: 'combat-1',
        name: 'Righteous Fury',
        description: 'Righteous Peck cards deal +2 damage.',
        art: '💥+',
        tree: 'Combat',
        cost: 1,
        unlocked: false,
        dependencies: [],
        position: { row: 1, col: 1 },
    },

    // --- MEMES TREE ---
    'memes-1': {
        id: 'memes-1',
        name: 'Dank Dogma',
        description: 'Being an outsider is cool. Gain +5 morale if you have fewer than 10 followers.',
        art: '😎',
        tree: 'Memes',
        cost: 1,
        unlocked: false,
        dependencies: [],
        position: { row: 1, col: 1 },
    },
    'memes-2': {
        id: 'memes-2',
        name: 'Holy Hashtag',
        description: 'Your propaganda is confusingly effective. Reduces rival heresy generation by 10%.',
        art: '#️⃣',
        tree: 'Memes',
        cost: 2,
        unlocked: false,
        dependencies: ['memes-1'],
        position: { row: 2, col: 1 },
    },
    'memes-3': {
        id: 'memes-3',
        name: 'Viral Sermon',
        description: 'Activate to double the effectiveness of your next Propaganda card.',
        art: '📈',
        tree: 'Memes',
        cost: 3,
        unlocked: false,
        dependencies: ['memes-2'],
        position: { row: 3, col: 1 },
        cooldown: 180,
    },
};